site_name: My Docs

repo_url: https://github.com/rytligc/docs.git

theme: 
  name: material

  features:
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.expand
      - header.autohide
      
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.highlight:
      linenums: true

  