site_name: My Docs

repo_url: https://github.com/rytligc/docs.git

theme: 
  name: material

  features:
      - navigation.tabs.sticky
      - navigation.instant
      - header.autohide
      
plugins:
  - search

markdown_extensions:
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem

  